-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 21:02:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Token` ;

CREATE TABLE IF NOT EXISTS `Token` (
  `idToken` INT NOT NULL,
  `Recuperacion_Contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idToken`),
  UNIQUE INDEX `Recuperacion_Contraseña_UNIQUE` (`Recuperacion_Contraseña` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombre` VARCHAR(200) NULL,
  `Apellido` VARCHAR(200) NULL,
  `Cedula` VARCHAR(200) NULL,
  `Correo` VARCHAR(200) NULL,
  `Pais` VARCHAR(200) NULL,
  `Estado` VARCHAR(200) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Roles_idRoles1` INT NOT NULL,
  `Token_idToken` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `Roles_idRoles1`),
  UNIQUE INDEX `Cedula_UNIQUE` (`Cedula` ASC) VISIBLE,
  UNIQUE INDEX `Contraseña_UNIQUE` (`Contraseña` ASC) VISIBLE,
  INDEX `fk_Usuarios_Token_idx` (`Token_idToken` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Token`
    FOREIGN KEY (`Token_idToken`)
    REFERENCES `Token` (`idToken`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

CREATE TABLE IF NOT EXISTS `Roles` (
  `idRoles` INT NOT NULL,
  `Administrador` VARCHAR(45) NULL,
  `Visitante` VARCHAR(45) NULL,
  `Visualizacion` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Usuarios_Roles_idRoles1` INT NOT NULL,
  PRIMARY KEY (`idRoles`),
  INDEX `fk_Roles_Usuarios1_idx` (`Usuarios_idUsuarios` ASC, `Usuarios_Roles_idRoles1` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios` , `Usuarios_Roles_idRoles1`)
    REFERENCES `Usuarios` (`idUsuarios` , `Roles_idRoles1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Redes_Sociales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Redes_Sociales` ;

CREATE TABLE IF NOT EXISTS `Redes_Sociales` (
  `idRedes_Sociales` INT NOT NULL,
  `X` VARCHAR(45) NULL,
  `Instagram` VARCHAR(45) NULL,
  `Tik_Tok` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  PRIMARY KEY (`idRedes_Sociales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuarios_has_Redes_Sociales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios_has_Redes_Sociales` ;

CREATE TABLE IF NOT EXISTS `Usuarios_has_Redes_Sociales` (
  `Usuarios_idUsuarios` INT NOT NULL,
  `Usuarios_Roles_idRoles1` INT NOT NULL,
  `Redes_Sociales_idRedes_Sociales` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Usuarios_Roles_idRoles1`, `Redes_Sociales_idRedes_Sociales`),
  INDEX `fk_Usuarios_has_Redes_Sociales_Redes_Sociales1_idx` (`Redes_Sociales_idRedes_Sociales` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Redes_Sociales_Usuarios1_idx` (`Usuarios_idUsuarios` ASC, `Usuarios_Roles_idRoles1` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Redes_Sociales_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios` , `Usuarios_Roles_idRoles1`)
    REFERENCES `Usuarios` (`idUsuarios` , `Roles_idRoles1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Redes_Sociales_Redes_Sociales1`
    FOREIGN KEY (`Redes_Sociales_idRedes_Sociales`)
    REFERENCES `Redes_Sociales` (`idRedes_Sociales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
